drop table if exists message;
drop table if exists user;

create table message (id bigint generated by default as identity, channel varchar(255) not null, date timestamp not null, text varchar(512) not null, sender bigint not null, primary key (id));
create table user (id bigint generated by default as identity, name varchar(255) not null, primary key (id));

insert into user (id, name) values (1, 'alice');
insert into user (id, name) values (2, 'wally');

insert into message (id, sender, channel, date, text) values (1, 1, 'main', current_date(), 'text');
insert into message (id, sender, channel, date, text) values (2, 2, 'main', current_date(), 'text');
insert into message (id, sender, channel, date, text) values (3, 2, 'main', current_date(), 'text');
